services:
  - type: web
    name: n8n
    env: docker
    docker:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_PROTOCOL
        value: https
    plan: free
